export default {
    START_FETCH_DRIVER_LIST:"START_FETCH_DRIVER_LIST",
    FETCH_DRIVER_LIST_SUCCESS:"FETCH_DRIVER_LIST_SUCCESS",
    FETCH_DRIVER_LIST_FAILED:"FETCH_DRIVER_LIST_FAILED",
    END_FETCH_DRIVER_LIST:"END_FETCH_DRIVER_LIST",
    OPEN_ADD_DRIVER_MODAL:"OPEN_ADD_DRIVER_MODAL",
    CLOSE_ADD_DRIVER_MODAL:"CLOSE_ADD_DRIVER_MODAL"
   
}